### PR TITLE
Update locality and neighbouhrood records in UAE

### PR DESCRIPTION
**Pull request by stepps00**
Will fix https://github.com/whosonfirst-data/whosonfirst-data/issues/2010.

This PR will:

- Add new neighbourhood polygons across the UAE
- Add new locality polygons across the UAE
- Clean up coastlines at each placetype (neighbourhood -> country)
- Standardize and clean up Arabic and English name properties
- Adjust "leftover" point geometries
- PIP each record to update hierarchies and parent_id values
- Validate all changes

### CODE REVIEW

**Comment by stepps00** [comment]
**Screenshots**

_Updated county and locality geometries_
Screen Shot 2022-09-20 at 10 36 40 AM

_All neighbourhood records in the UAE_
Screen Shot 2022-09-20 at 10 37 16 AM

_Updated coastline geometries around Dubai_
Screen Shot 2022-09-20 at 10 37 41 AM

_Updated coastline geometries around Ras Al-Khaimah_
Screen Shot 2022-09-20 at 10 38 05 AM

**Comment by stepps00** [comment]
The most recent commits take care of some issues found when reviewing these changes (adding polygons to localities along the coast and major highways, adding placetype_alt and is_funky properties to a handful of records, and adding some missing islands to relevant geometries).

@nvkelso this PR is ready for another review - I'll start on the PIP work and add name translations shortly.

**Review by nvkelso — APPROVED** [review]
We reviewed heads up, and I've spot checked these change. LGTM – huge improvement. 

I'd like to see the name localization added, too, either to this PR or in quick follow.

**Comment by stepps00** [comment]
The most recent commit added Arabic name properties, and adjusted existing values.. I'm going to PIP the PR and validate changes, then merge if all the changes look good.

**Comment by stepps00** [comment]
I noticed some unexpected results in the PIP results, so I investigated and see there are a handful of records with geometries in incorrect projections, example: https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-ae/stepps00/admin-improvements/data/856/679/83/85667983.geojson

Will add a new commit shortly to fix..

**Comment by stepps00** [comment]
I've reviewed all of the changes once more, they look good. Merging.

**Pull request merged**
