### PR TITLE
WIP: Wiki names import

### PR DESCRIPTION
**Pull request by stepps00**
WIP

Will fix the AE portion of https://github.com/whosonfirst-data/whosonfirst-data/issues/1656.

This PR uses existing tools/logic to import new name translations for any record in this repository. 

Since the import logic is slightly modified, there were additional checks on the names being imported; the result should still give us nice, shiny translations for all placetypes.

### CODE REVIEW

**Comment by nvkelso** [comment]
Please also add the stats for names added per language... and list out any "big cities" that have a population_rank threshold to manually review.

**Comment by stepps00** [comment]
I'm rerunning the script with a new [population_rank](https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/wof#population_rank) check to flag any record with a population rank over 10. I'll also paste the amount of name translations per language in a table below.

In other PRs I'll omit the table, but store the counts and store them in a cookbook doc/blog.

**Comment by stepps00** [comment]
lang | count
--|--
afr | 3
als | 3
ang | 3
ara | 17
arg | 1
arz | 5
ast | 10
azb | 8
aze | 5
bak | 1
bar | 1
bel | 5
ben | 6
bho | 1
bih | 5
bos | 1
bpy | 3
bre | 3
bul | 3
cat | 17
ceb | 29
ces | 5
ckb | 1
cos | 1
cym | 1
dan | 4
deu | 14
diq | 1
ell | 9
eng | 6
epo | 16
est | 5
eus | 6
fas | 51
fin | 8
fra | 13
frr | 7
glg | 1
gom | 1
guj | 3
heb | 4
hin | 5
hrv | 4
hun | 4
hye | 4
hyw | 10
ind | 18
inh | 2
ita | 21
jav | 1
jpn | 12
kab | 1
kan | 3
kat | 2
kaz | 1
kor | 10
kur | 1
lat | 3
lav | 5
lfn | 1
lij | 2
lit | 9
lmo | 6
ltz | 2
lzh | 1
mal | 6
mar | 4
mkd | 5
mlg | 2
mon | 2
msa | 8
mwl | 1
nah | 2
nan | 14
nds | 1
nep | 1
new | 2
nld | 17
nno | 56
nob | 2
nor | 23
ori | 1
pan | 5
pms | 3
pnb | 16
pol | 11
por | 18
pus | 2
ron | 5
rus | 10
san | 1
sat | 1
sco | 7
sin | 2
slk | 3
slv | 1
smo | 1
snd | 2
spa | 13
sqi | 2
srp | 6
swa | 7
swe | 17
szl | 1
tam | 8
tat | 3
tel | 3
tgk | 1
tgl | 5
tha | 3
tur | 10
ukr | 11
urd | 23
uzb | 2
vie | 21
war | 4
wuu | 4
xmf | 15
yor | 3
yue | 17
zho | 9


Records to review:
85632573
85667981
85667983
85667977
1376833603
421168683
421174961
421179641

**Comment by stepps00** [comment]
I reviewed the records above and all added names look correct. This should be good to merge, but I'm going to apply the same script to another repo or two before merging in case anything odd pops up.

**Pull request merged**
